/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Firm = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'size' : IDL.Variant({
    'big4' : IDL.Null,
    'midSize' : IDL.Null,
    'small' : IDL.Null,
  }),
  'description' : IDL.Text,
  'website' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CSVJobInput = IDL.Record({
  'title' : IDL.Text,
  'firmName' : IDL.Text,
  'isOpen' : IDL.Text,
  'category' : IDL.Text,
  'postingUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const EmploymentType = IDL.Variant({
  'internship' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const JobCategory = IDL.Variant({
  'tax' : IDL.Null,
  'accounting' : IDL.Null,
  'audit' : IDL.Null,
  'analytics' : IDL.Null,
});
export const JobPostingInput = IDL.Record({
  'title' : IDL.Text,
  'firmName' : IDL.Text,
  'isOpen' : IDL.Bool,
  'employmentType' : IDL.Opt(EmploymentType),
  'firmId' : IDL.Nat,
  'datePosted' : IDL.Opt(IDL.Nat),
  'category' : JobCategory,
  'postingUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'firmName' : IDL.Text,
  'isOpen' : IDL.Bool,
  'employmentType' : IDL.Opt(EmploymentType),
  'firmId' : IDL.Nat,
  'datePosted' : IDL.Opt(IDL.Nat),
  'category' : JobCategory,
  'postingUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'notApplied' : IDL.Null,
  'offer' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'interviewing' : IDL.Null,
  'withdrawn' : IDL.Null,
});
export const JobTracking = IDL.Record({
  'jobPostingId' : IDL.Nat,
  'lastUpdated' : IDL.Nat,
  'saved' : IDL.Bool,
  'applicationStatus' : ApplicationStatus,
  'notes' : IDL.Text,
});
export const JobTrackingInput = IDL.Record({
  'jobPostingId' : IDL.Nat,
  'saved' : IDL.Bool,
  'applicationStatus' : ApplicationStatus,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateFirm' : IDL.Func([Firm], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportJobs' : IDL.Func([IDL.Vec(CSVJobInput)], [IDL.Nat], []),
  'closeJobPosting' : IDL.Func([IDL.Nat], [], []),
  'createOrUpdateJobPosting' : IDL.Func([JobPostingInput], [IDL.Nat], []),
  'getAllFirms' : IDL.Func([], [IDL.Vec(Firm)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllOpenJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobPostingTrend' : IDL.Func(
      [],
      [
        IDL.Record({
          'olderPostings' : IDL.Nat,
          'trend' : IDL.Text,
          'recentPostings' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOpenJobsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getOpenJobsByFirm' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserJobTracking' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobTracking)],
      ['query'],
    ),
  'getUserJobsByStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJobTracking' : IDL.Func([JobTrackingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Firm = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'size' : IDL.Variant({
      'big4' : IDL.Null,
      'midSize' : IDL.Null,
      'small' : IDL.Null,
    }),
    'description' : IDL.Text,
    'website' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CSVJobInput = IDL.Record({
    'title' : IDL.Text,
    'firmName' : IDL.Text,
    'isOpen' : IDL.Text,
    'category' : IDL.Text,
    'postingUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const EmploymentType = IDL.Variant({
    'internship' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const JobCategory = IDL.Variant({
    'tax' : IDL.Null,
    'accounting' : IDL.Null,
    'audit' : IDL.Null,
    'analytics' : IDL.Null,
  });
  const JobPostingInput = IDL.Record({
    'title' : IDL.Text,
    'firmName' : IDL.Text,
    'isOpen' : IDL.Bool,
    'employmentType' : IDL.Opt(EmploymentType),
    'firmId' : IDL.Nat,
    'datePosted' : IDL.Opt(IDL.Nat),
    'category' : JobCategory,
    'postingUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'firmName' : IDL.Text,
    'isOpen' : IDL.Bool,
    'employmentType' : IDL.Opt(EmploymentType),
    'firmId' : IDL.Nat,
    'datePosted' : IDL.Opt(IDL.Nat),
    'category' : JobCategory,
    'postingUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ApplicationStatus = IDL.Variant({
    'notApplied' : IDL.Null,
    'offer' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'interviewing' : IDL.Null,
    'withdrawn' : IDL.Null,
  });
  const JobTracking = IDL.Record({
    'jobPostingId' : IDL.Nat,
    'lastUpdated' : IDL.Nat,
    'saved' : IDL.Bool,
    'applicationStatus' : ApplicationStatus,
    'notes' : IDL.Text,
  });
  const JobTrackingInput = IDL.Record({
    'jobPostingId' : IDL.Nat,
    'saved' : IDL.Bool,
    'applicationStatus' : ApplicationStatus,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateFirm' : IDL.Func([Firm], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportJobs' : IDL.Func([IDL.Vec(CSVJobInput)], [IDL.Nat], []),
    'closeJobPosting' : IDL.Func([IDL.Nat], [], []),
    'createOrUpdateJobPosting' : IDL.Func([JobPostingInput], [IDL.Nat], []),
    'getAllFirms' : IDL.Func([], [IDL.Vec(Firm)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllOpenJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobPostingTrend' : IDL.Func(
        [],
        [
          IDL.Record({
            'olderPostings' : IDL.Nat,
            'trend' : IDL.Text,
            'recentPostings' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOpenJobsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getOpenJobsByFirm' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserJobTracking' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobTracking)],
        ['query'],
      ),
    'getUserJobsByStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJobTracking' : IDL.Func([JobTrackingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };