/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'notApplied' : null } |
  { 'offer' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'interviewing' : null } |
  { 'withdrawn' : null };
export interface CSVJobInput {
  'title' : string,
  'firmName' : string,
  'isOpen' : string,
  'category' : string,
  'postingUrl' : string,
  'location' : string,
}
export type EmploymentType = { 'internship' : null } |
  { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface Firm {
  'id' : bigint,
  'name' : string,
  'size' : { 'big4' : null } |
    { 'midSize' : null } |
    { 'small' : null },
  'description' : string,
  'website' : string,
}
export type JobCategory = { 'tax' : null } |
  { 'accounting' : null } |
  { 'audit' : null } |
  { 'analytics' : null };
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'firmName' : string,
  'isOpen' : boolean,
  'employmentType' : [] | [EmploymentType],
  'firmId' : bigint,
  'datePosted' : [] | [bigint],
  'category' : JobCategory,
  'postingUrl' : string,
  'location' : string,
}
export interface JobPostingInput {
  'title' : string,
  'firmName' : string,
  'isOpen' : boolean,
  'employmentType' : [] | [EmploymentType],
  'firmId' : bigint,
  'datePosted' : [] | [bigint],
  'category' : JobCategory,
  'postingUrl' : string,
  'location' : string,
}
export interface JobTracking {
  'jobPostingId' : bigint,
  'lastUpdated' : bigint,
  'saved' : boolean,
  'applicationStatus' : ApplicationStatus,
  'notes' : string,
}
export interface JobTrackingInput {
  'jobPostingId' : bigint,
  'saved' : boolean,
  'applicationStatus' : ApplicationStatus,
  'notes' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateFirm' : ActorMethod<[Firm], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportJobs' : ActorMethod<[Array<CSVJobInput>], bigint>,
  'closeJobPosting' : ActorMethod<[bigint], undefined>,
  'createOrUpdateJobPosting' : ActorMethod<[JobPostingInput], bigint>,
  'getAllFirms' : ActorMethod<[], Array<Firm>>,
  'getAllJobs' : ActorMethod<[], Array<JobPosting>>,
  'getAllOpenJobs' : ActorMethod<[], Array<JobPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobPostingTrend' : ActorMethod<
    [],
    { 'olderPostings' : bigint, 'trend' : string, 'recentPostings' : bigint }
  >,
  'getOpenJobsByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getOpenJobsByFirm' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserJobTracking' : ActorMethod<[Principal], Array<JobTracking>>,
  'getUserJobsByStatus' : ActorMethod<[Principal], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJobTracking' : ActorMethod<[JobTrackingInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];