/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CSVJobInput {
    title: string;
    firmName: string;
    isOpen: string;
    category: string;
    postingUrl: string;
    location: string;
}
export interface JobTracking {
    jobPostingId: bigint;
    lastUpdated: bigint;
    saved: boolean;
    applicationStatus: ApplicationStatus;
    notes: string;
}
export interface Firm {
    id: bigint;
    name: string;
    size: Variant_big4_midSize_small;
    description: string;
    website: string;
}
export interface JobPosting {
    id: bigint;
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType?: EmploymentType;
    firmId: bigint;
    datePosted?: bigint;
    category: JobCategory;
    postingUrl: string;
    location: string;
}
export interface JobPostingInput {
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType?: EmploymentType;
    firmId: bigint;
    datePosted?: bigint;
    category: JobCategory;
    postingUrl: string;
    location: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface JobTrackingInput {
    jobPostingId: bigint;
    saved: boolean;
    applicationStatus: ApplicationStatus;
    notes: string;
}
export enum ApplicationStatus {
    notApplied = "notApplied",
    offer = "offer",
    applied = "applied",
    rejected = "rejected",
    interviewing = "interviewing",
    withdrawn = "withdrawn"
}
export enum EmploymentType {
    internship = "internship",
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum JobCategory {
    tax = "tax",
    accounting = "accounting",
    audit = "audit",
    analytics = "analytics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_big4_midSize_small {
    big4 = "big4",
    midSize = "midSize",
    small = "small"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateFirm(firm: Firm): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportJobs(csvData: Array<CSVJobInput>): Promise<bigint>;
    closeJobPosting(jobId: bigint): Promise<void>;
    createOrUpdateJobPosting(input: JobPostingInput): Promise<bigint>;
    getAllFirms(): Promise<Array<Firm>>;
    getAllJobs(): Promise<Array<JobPosting>>;
    getAllOpenJobs(): Promise<Array<JobPosting>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobPostingTrend(): Promise<{
        olderPostings: bigint;
        trend: string;
        recentPostings: bigint;
    }>;
    getOpenJobsByCategory(): Promise<Array<[string, bigint]>>;
    getOpenJobsByFirm(): Promise<Array<[string, bigint]>>;
    getUserJobTracking(user: Principal): Promise<Array<JobTracking>>;
    getUserJobsByStatus(user: Principal): Promise<Array<[string, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveJobTracking(tracking: JobTrackingInput): Promise<void>;
}
import type { ApplicationStatus as _ApplicationStatus, EmploymentType as _EmploymentType, Firm as _Firm, JobCategory as _JobCategory, JobPosting as _JobPosting, JobPostingInput as _JobPostingInput, JobTracking as _JobTracking, JobTrackingInput as _JobTrackingInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateFirm(arg0: Firm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateFirm(to_candid_Firm_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateFirm(to_candid_Firm_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportJobs(arg0: Array<CSVJobInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportJobs(arg0);
            return result;
        }
    }
    async closeJobPosting(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeJobPosting(arg0);
            return result;
        }
    }
    async createOrUpdateJobPosting(arg0: JobPostingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateJobPosting(to_candid_JobPostingInput_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateJobPosting(to_candid_JobPostingInput_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllFirms(): Promise<Array<Firm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFirms();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFirms();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobs(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOpenJobs(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenJobs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenJobs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPostingTrend(): Promise<{
        olderPostings: bigint;
        trend: string;
        recentPostings: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPostingTrend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPostingTrend();
            return result;
        }
    }
    async getOpenJobsByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenJobsByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenJobsByCategory();
            return result;
        }
    }
    async getOpenJobsByFirm(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenJobsByFirm();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenJobsByFirm();
            return result;
        }
    }
    async getUserJobTracking(arg0: Principal): Promise<Array<JobTracking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJobTracking(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJobTracking(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserJobsByStatus(arg0: Principal): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJobsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJobsByStatus(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveJobTracking(arg0: JobTrackingInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJobTracking(to_candid_JobTrackingInput_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJobTracking(to_candid_JobTrackingInput_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Firm_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Firm): Firm {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobCategory): JobCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_JobTracking_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobTracking): JobTracking {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmploymentType]): EmploymentType | null {
    return value.length === 0 ? null : from_candid_EmploymentType_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    size: {
        big4: null;
    } | {
        midSize: null;
    } | {
        small: null;
    };
    description: string;
    website: string;
}): {
    id: bigint;
    name: string;
    size: Variant_big4_midSize_small;
    description: string;
    website: string;
} {
    return {
        id: value.id,
        name: value.name,
        size: from_candid_variant_n15(_uploadFile, _downloadFile, value.size),
        description: value.description,
        website: value.website
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType: [] | [_EmploymentType];
    firmId: bigint;
    datePosted: [] | [bigint];
    category: _JobCategory;
    postingUrl: string;
    location: string;
}): {
    id: bigint;
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType?: EmploymentType;
    firmId: bigint;
    datePosted?: bigint;
    category: JobCategory;
    postingUrl: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        firmName: value.firmName,
        isOpen: value.isOpen,
        employmentType: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.employmentType)),
        firmId: value.firmId,
        datePosted: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.datePosted)),
        category: from_candid_JobCategory_n23(_uploadFile, _downloadFile, value.category),
        postingUrl: value.postingUrl,
        location: value.location
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobPostingId: bigint;
    lastUpdated: bigint;
    saved: boolean;
    applicationStatus: _ApplicationStatus;
    notes: string;
}): {
    jobPostingId: bigint;
    lastUpdated: bigint;
    saved: boolean;
    applicationStatus: ApplicationStatus;
    notes: string;
} {
    return {
        jobPostingId: value.jobPostingId,
        lastUpdated: value.lastUpdated,
        saved: value.saved,
        applicationStatus: from_candid_ApplicationStatus_n31(_uploadFile, _downloadFile, value.applicationStatus),
        notes: value.notes
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    big4: null;
} | {
    midSize: null;
} | {
    small: null;
}): Variant_big4_midSize_small {
    return "big4" in value ? Variant_big4_midSize_small.big4 : "midSize" in value ? Variant_big4_midSize_small.midSize : "small" in value ? Variant_big4_midSize_small.small : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): EmploymentType {
    return "internship" in value ? EmploymentType.internship : "contract" in value ? EmploymentType.contract : "partTime" in value ? EmploymentType.partTime : "fullTime" in value ? EmploymentType.fullTime : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: null;
} | {
    accounting: null;
} | {
    audit: null;
} | {
    analytics: null;
}): JobCategory {
    return "tax" in value ? JobCategory.tax : "accounting" in value ? JobCategory.accounting : "audit" in value ? JobCategory.audit : "analytics" in value ? JobCategory.analytics : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notApplied: null;
} | {
    offer: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    interviewing: null;
} | {
    withdrawn: null;
}): ApplicationStatus {
    return "notApplied" in value ? ApplicationStatus.notApplied : "offer" in value ? ApplicationStatus.offer : "applied" in value ? ApplicationStatus.applied : "rejected" in value ? ApplicationStatus.rejected : "interviewing" in value ? ApplicationStatus.interviewing : "withdrawn" in value ? ApplicationStatus.withdrawn : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Firm>): Array<Firm> {
    return value.map((x)=>from_candid_Firm_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobTracking>): Array<JobTracking> {
    return value.map((x)=>from_candid_JobTracking_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Firm_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Firm): _Firm {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobCategory): _JobCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_JobPostingInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPostingInput): _JobPostingInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_JobTrackingInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobTrackingInput): _JobTrackingInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    size: Variant_big4_midSize_small;
    description: string;
    website: string;
}): {
    id: bigint;
    name: string;
    size: {
        big4: null;
    } | {
        midSize: null;
    } | {
        small: null;
    };
    description: string;
    website: string;
} {
    return {
        id: value.id,
        name: value.name,
        size: to_candid_variant_n3(_uploadFile, _downloadFile, value.size),
        description: value.description,
        website: value.website
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobPostingId: bigint;
    saved: boolean;
    applicationStatus: ApplicationStatus;
    notes: string;
}): {
    jobPostingId: bigint;
    saved: boolean;
    applicationStatus: _ApplicationStatus;
    notes: string;
} {
    return {
        jobPostingId: value.jobPostingId,
        saved: value.saved,
        applicationStatus: to_candid_ApplicationStatus_n35(_uploadFile, _downloadFile, value.applicationStatus),
        notes: value.notes
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType?: EmploymentType;
    firmId: bigint;
    datePosted?: bigint;
    category: JobCategory;
    postingUrl: string;
    location: string;
}): {
    title: string;
    firmName: string;
    isOpen: boolean;
    employmentType: [] | [_EmploymentType];
    firmId: bigint;
    datePosted: [] | [bigint];
    category: _JobCategory;
    postingUrl: string;
    location: string;
} {
    return {
        title: value.title,
        firmName: value.firmName,
        isOpen: value.isOpen,
        employmentType: value.employmentType ? candid_some(to_candid_EmploymentType_n8(_uploadFile, _downloadFile, value.employmentType)) : candid_none(),
        firmId: value.firmId,
        datePosted: value.datePosted ? candid_some(value.datePosted) : candid_none(),
        category: to_candid_JobCategory_n10(_uploadFile, _downloadFile, value.category),
        postingUrl: value.postingUrl,
        location: value.location
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobCategory): {
    tax: null;
} | {
    accounting: null;
} | {
    audit: null;
} | {
    analytics: null;
} {
    return value == JobCategory.tax ? {
        tax: null
    } : value == JobCategory.accounting ? {
        accounting: null
    } : value == JobCategory.audit ? {
        audit: null
    } : value == JobCategory.analytics ? {
        analytics: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_big4_midSize_small): {
    big4: null;
} | {
    midSize: null;
} | {
    small: null;
} {
    return value == Variant_big4_midSize_small.big4 ? {
        big4: null
    } : value == Variant_big4_midSize_small.midSize ? {
        midSize: null
    } : value == Variant_big4_midSize_small.small ? {
        small: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    notApplied: null;
} | {
    offer: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    interviewing: null;
} | {
    withdrawn: null;
} {
    return value == ApplicationStatus.notApplied ? {
        notApplied: null
    } : value == ApplicationStatus.offer ? {
        offer: null
    } : value == ApplicationStatus.applied ? {
        applied: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.interviewing ? {
        interviewing: null
    } : value == ApplicationStatus.withdrawn ? {
        withdrawn: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == EmploymentType.internship ? {
        internship: null
    } : value == EmploymentType.contract ? {
        contract: null
    } : value == EmploymentType.partTime ? {
        partTime: null
    } : value == EmploymentType.fullTime ? {
        fullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
